### ISSUE TITLE
1.2 use hash_file (SHA-2) instead of MD5 or SHA-1

### ISSUE THREAD

**Issue by DanielRuf** [johnnymast/redbox-scan#38]
`hash_file` supports a wider range of algorithms and it would be better to use some algorithm which has no collissions. MD% and SHA-1 are broken (at least MD5 since 2004 or earlier, published by Xiaoyun Wang) and collissions can be easily created.

http://www.mathstat.dal.ca/~selinger/md5collision/
http://natmchugh.blogspot.de/2015/02/create-your-own-md5-collisions.html (cost ~ 1 USD)
http://www.bishopfox.com/resources/tools/other-free-tools/md4md5-collision-code/

http://crypto.stackexchange.com/questions/1434/are-there-two-known-strings-which-have-the-same-md5-hash-value

Algorithms from the SHA-2 family are much better and no collissions are known for them.

Alternatively `openssl_digest` for strings can be used too.

http://ideone.com/xHtUfP
http://ideone.com/oDcX7n

Sure it is slower but any algorithm from the SHA-2 family ensures file integrity and (so far) is safe against collissions.

PS: PHP 5.3 and 5.4 shouldn't be used / supported anymore ;-)

**Comment by johnnymast** [comment]
Interesting .. I will look into this for the 1.2 milestone.
